#!/usr/bin/env python3
"""
Generate missing Airflow secrets in .env for local development.
Safe to run multiple times — only writes keys that are absent or empty.
Prints the generated admin password on first run.
"""
import base64
import os
import secrets
from pathlib import Path

ENV_FILE = Path(__file__).resolve().parent.parent / ".env"


def _fernet_key() -> str:
    return base64.urlsafe_b64encode(os.urandom(32)).decode()


def _read_existing(path: Path) -> dict:
    if not path.exists():
        return {}
    result = {}
    for line in path.read_text().splitlines():
        line = line.strip()
        if line.startswith("#") or "=" not in line:
            continue
        key, _, val = line.partition("=")
        result[key.strip()] = val.strip()
    return result


def main() -> None:
    existing = _read_existing(ENV_FILE)

    password = secrets.token_urlsafe(16)
    candidates = {
        "AIRFLOW__DATABASE__SQL_ALCHEMY_CONN": "postgresql+psycopg2://airflow:airflow@postgres/airflow",
        "AIRFLOW__CELERY__RESULT_BACKEND":     "db+postgresql://airflow:airflow@postgres/airflow",
        "AIRFLOW__CELERY__BROKER_URL":         "redis://:@redis:6379/0",
        "AIRFLOW__CORE__FERNET_KEY":           _fernet_key(),
        "AIRFLOW__API_AUTH__JWT_SECRET":       secrets.token_hex(32),
        "_AIRFLOW_WWW_USER_USERNAME":          "airflow",
        "_AIRFLOW_WWW_USER_PASSWORD":          password,
    }

    to_write = {k: v for k, v in candidates.items() if not existing.get(k)}

    if not to_write:
        print("[gen_local_env] All Airflow keys present — nothing to do.")
        return

    with ENV_FILE.open("a") as f:
        if ENV_FILE.exists() and ENV_FILE.stat().st_size > 0:
            f.write("\n")
        f.write("# Airflow secrets (auto-generated by scripts/gen_local_env.py)\n")
        for key, value in to_write.items():
            f.write(f"{key}={value}\n")

    print(f"[gen_local_env] Wrote {len(to_write)} key(s) to {ENV_FILE}")
    if "_AIRFLOW_WWW_USER_PASSWORD" in to_write:
        print(f"[gen_local_env] Airflow admin password: {to_write['_AIRFLOW_WWW_USER_PASSWORD']}")


if __name__ == "__main__":
    main()
